const sql=require('../../config/database');
function dates(from,to){return {from:from||'1900-01-01',to:to||'2999-12-31'};}
async function production(from,to){const d=dates(from,to);return sql`SELECT pr.production_at::date AS date,p.name AS product,u.full_name AS operator,pr.shift,SUM(pr.quantity)::float8 AS quantity FROM production_records pr JOIN products p ON p.id=pr.product_id JOIN users u ON u.id=pr.operator_id WHERE pr.production_at::date BETWEEN ${d.from}::date AND ${d.to}::date GROUP BY date,p.name,u.full_name,pr.shift ORDER BY date DESC,p.name`;}
async function sales(from,to){const d=dates(from,to);return sql`SELECT s.sold_at::date AS date,c.name AS customer,u.full_name AS operator,s.payment_type AS "paymentType",SUM(s.total_amount)::float8 AS total FROM sales s JOIN customers c ON c.id=s.customer_id JOIN users u ON u.id=s.operator_id WHERE s.sold_at::date BETWEEN ${d.from}::date AND ${d.to}::date GROUP BY date,c.name,u.full_name,s.payment_type ORDER BY date DESC,c.name`;}
async function debtors(){return sql`SELECT customer_id AS "customerId",name,phone,sales_total::float8 AS "salesTotal",payments_total::float8 AS "paymentsTotal",balance::float8 AS balance FROM v_customer_balances WHERE balance>0 ORDER BY balance DESC`;}
async function operators(from,to){const d=dates(from,to);return sql`SELECT u.id,u.full_name AS "operatorName",COALESCE(p.production_count,0)::int AS "productionCount",COALESCE(p.production_qty,0)::float8 AS "productionQuantity",COALESCE(s.sales_count,0)::int AS "salesCount",COALESCE(s.sales_total,0)::float8 AS "salesTotal" FROM users u LEFT JOIN (SELECT operator_id,COUNT(*) production_count,SUM(quantity) production_qty FROM production_records WHERE production_at::date BETWEEN ${d.from}::date AND ${d.to}::date GROUP BY operator_id) p ON p.operator_id=u.id LEFT JOIN (SELECT operator_id,COUNT(*) sales_count,SUM(total_amount) sales_total FROM sales WHERE sold_at::date BETWEEN ${d.from}::date AND ${d.to}::date GROUP BY operator_id) s ON s.operator_id=u.id WHERE u.role='OPERATOR' ORDER BY u.full_name`;}
async function productionMonthly(from,to){const d=dates(from,to);return sql`SELECT date_trunc('month',production_at)::date AS month,SUM(quantity)::float8 AS total FROM production_records WHERE production_at::date BETWEEN ${d.from}::date AND ${d.to}::date GROUP BY 1 ORDER BY 1 DESC`;}
async function salesMonthly(from,to){const d=dates(from,to);return sql`SELECT date_trunc('month',sold_at)::date AS month,SUM(total_amount)::float8 AS total FROM sales WHERE sold_at::date BETWEEN ${d.from}::date AND ${d.to}::date GROUP BY 1 ORDER BY 1 DESC`;}
async function inventory(){return sql`SELECT product_id AS "productId",code,name,unit,stock::float8 AS stock,minimum_stock::float8 AS "minimumStock",price::float8 AS price,(stock*price)::float8 AS "stockValue" FROM v_inventory_stock ORDER BY name`;}
module.exports={production,sales,productionMonthly,salesMonthly,debtors,operators,inventory};
