const ROLES = Object.freeze({ MANAGER: 'MANAGER', OPERATOR: 'OPERATOR' });
const PAYMENT_TYPES = Object.freeze({ CASH: 'CASH', CARD: 'CARD', CREDIT: 'CREDIT', MIXED: 'MIXED' });
const INVENTORY_TYPES = Object.freeze({
  OPENING: 'OPENING',
  PRODUCTION: 'PRODUCTION',
  SALE: 'SALE',
  ADJUSTMENT_IN: 'ADJUSTMENT_IN',
  ADJUSTMENT_OUT: 'ADJUSTMENT_OUT'
});

module.exports = { ROLES, PAYMENT_TYPES, INVENTORY_TYPES };
