import {useEffect,useState} from 'react';
import api from '../services/api';
import {Page,ErrorBox} from '../components/Ui';
import SaleEntry from '../components/SaleEntry';
import {useAuth} from '../context/AuthContext';

export default function OperatorPanel(){
  const {isManager}=useAuth();
  const [mode,setMode]=useState('start'),[products,setProducts]=useState([]),[customers,setCustomers]=useState([]),[status,setStatus]=useState(null),[error,setError]=useState(null),[ok,setOk]=useState(''),[busy,setBusy]=useState(false);
  const [start,setStart]=useState({productId:'',counterStart:'',note:''}),[end,setEnd]=useState({defects:'',note:''});
  async function load(){try{setError(null);const [p,c,s]=await Promise.all([api.get('/products'),api.get('/customers'),api.get('/production/status')]);setProducts(p.data.filter(x=>x.isActive));setCustomers(c.data.filter(x=>x.isActive));setStatus(s.data)}catch(e){setError(e)}}
  useEffect(()=>{load()},[]);
  async function run(fn,msg){setBusy(true);setError(null);setOk('');try{await fn();setOk(msg);await load()}catch(e){setError(e)}finally{setBusy(false)}}
  async function submitStart(e){e.preventDefault();run(()=>api.post('/production/start',{...start,counterStart:Number(start.counterStart)}),'کانتر شروع ثبت شد. سیستم تا ۱۵ دقیقه قبل یا بعد از شروع رسمی شیفت را می‌پذیرد.');}
  async function submitEnd(e){e.preventDefault();run(()=>api.post('/production/end',{...end,defects:Number(end.defects)}),'تعداد معیوب ثبت شد. تولید با کانتر شروع شیفت بعد نهایی می‌شود.');}
  return <Page title={isManager?'عملیات روزانه مدیریت':'پنل عملیات اپراتور'}><ErrorBox error={error}/>{ok&&<div className="success">{ok}</div>}<div className="operator-status panel"><b>وضعیت شیفت:</b> {status?<span>{status.shiftName} — {status.productName} — کانتر شروع {Number(status.startCounter).toLocaleString('fa-IR')} — {status.status}</span>:<span>{isManager?'برای حساب مدیر شیفت شخصی تعریف نشده؛ می‌توانید عملیات جاری را ثبت کنید.':'شیفت باز ثبت‌شده‌ای ندارید.'}</span>}</div><div className="operator-actions"><button className={mode==='start'?'active-action':'ghost'} onClick={()=>setMode('start')}>شروع شیفت / کانتر</button><button className={mode==='end'?'active-action':'ghost'} onClick={()=>setMode('end')}>پایان شیفت / معیوب</button><button className={mode==='sale'?'active-action':'ghost'} onClick={()=>setMode('sale')}>ثبت فروش</button></div>{mode==='start'&&<form className="panel operator-form" onSubmit={submitStart}><h3>شروع شیفت و ثبت کانتر</h3><div className="hint">ثبت کانتر شروع تا ۱۵ دقیقه زودتر یا دیرتر از زمان رسمی شیفت مجاز است.</div><label>نوع محصول<select required value={start.productId} onChange={e=>setStart({...start,productId:e.target.value})}><option value="">انتخاب کنید</option>{products.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>عدد فعلی کانتر دستگاه<input required inputMode="numeric" type="number" min="0" step="1" value={start.counterStart} onChange={e=>setStart({...start,counterStart:e.target.value})}/></label><label>توضیح اختیاری<textarea value={start.note} onChange={e=>setStart({...start,note:e.target.value})}/></label><button disabled={busy}>ثبت شروع شیفت</button></form>}{mode==='end'&&<form className="panel operator-form" onSubmit={submitEnd}><h3>پایان شیفت و ثبت معیوب</h3><label>تعداد سبد معیوب<input required inputMode="numeric" type="number" min="0" step="1" value={end.defects} onChange={e=>setEnd({...end,defects:e.target.value})}/></label><label>توضیح اختیاری<textarea value={end.note} onChange={e=>setEnd({...end,note:e.target.value})}/></label><button disabled={busy}>ثبت معیوب</button></form>}{mode==='sale'&&<SaleEntry products={products} customers={customers} setCustomers={setCustomers} onSaved={load} busy={busy} setBusy={setBusy} setError={setError} setOk={setOk}/>}</Page>
}
