import NumericInput from '../components/NumericInput';
import {useEffect,useState} from 'react';
import api from '../services/api';
import {Page,ErrorBox} from '../components/Ui';
import SaleEntry from '../components/SaleEntry';
import {shiftStatusLabel,toNumber,normalizeDigits} from '../utils/fa';

export default function OperatorPanel(){
  const [mode,setMode]=useState('start'),[products,setProducts]=useState([]),[customers,setCustomers]=useState([]),[status,setStatus]=useState(null),[error,setError]=useState(null),[ok,setOk]=useState(''),[busy,setBusy]=useState(false);
  const [start,setStart]=useState({productId:'',counterStart:'',note:''}),[end,setEnd]=useState({defects:'',note:'',cleaningDone:false});
  async function load(){try{setError(null);const [p,c,s]=await Promise.all([api.get('/products'),api.get('/customers'),api.get('/production/status')]);setProducts(p.data.filter(x=>x.isActive));setCustomers(c.data.filter(x=>x.isActive));setStatus(s.data)}catch(e){setError(e)}}
  useEffect(()=>{load()},[]);
  async function run(fn,msg){setBusy(true);setError(null);setOk('');try{await fn();setOk(msg);await load()}catch(e){setError(e)}finally{setBusy(false)}}
  async function submitStart(e){e.preventDefault();const counter=normalizeDigits(start.counterStart);if(!/^\d{7}$/.test(counter)){setError(new Error('کانتر دستگاه باید دقیقاً ۷ رقم باشد؛ صفرهای ابتدای عدد را نیز وارد کنید.'));return;}run(()=>api.post('/production/start',{...start,counterStart:counter}),'کانتر شروع شیفت ثبت شد.');}
  async function submitEnd(e){e.preventDefault();run(async()=>{await api.post('/production/end',{...end,defects:toNumber(end.defects)});setEnd({defects:'',note:'',cleaningDone:false})},'تعداد سبدهای معیوب و وضعیت نظافت ثبت شد. تولید با ثبت کانتر شروع شیفت بعد نهایی می‌شود.');}
  return <Page title="پنل عملیات اپراتور"><ErrorBox error={error}/>{ok&&<div className="success">{ok}</div>}
    <div className="operator-status panel"><b>وضعیت شیفت:</b> {status?<span>{status.shiftName} — {status.productName} — کانتر شروع {Number(status.startCounter).toLocaleString('fa-IR')} — {shiftStatusLabel[status.status]||status.status}</span>:<span>شیفت باز ثبت‌شده‌ای ندارید.</span>}</div>
    <div className="operator-actions"><button className={mode==='start'?'active-action':'ghost'} onClick={()=>setMode('start')}>شروع شیفت / ثبت کانتر</button><button className={mode==='end'?'active-action':'ghost'} onClick={()=>setMode('end')}>پایان شیفت / ثبت معیوب</button><button className={`sale-action ${mode==='sale'?'selected':''}`} onClick={()=>setMode('sale')}>ثبت فروش</button></div>
    {mode==='start'&&<form className="panel operator-form" onSubmit={submitStart}><h3>شروع شیفت و ثبت کانتر</h3><div className="hint">عدد کانتر شروع را در ابتدای شیفت وارد کنید. ثبت کانتر به منزله ثبت حضور شما در شیفت است. اگر شروع کار با تأخیر انجام شد، کانتر را به محض شروع کار ثبت کنید.</div><label>نوع محصول<select required value={start.productId} onChange={e=>setStart({...start,productId:e.target.value})}><option value="">انتخاب کنید</option>{products.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>عدد فعلی کانتر دستگاه<NumericInput required inputMode="numeric" type="text" value={start.counterStart} onChange={e=>setStart({...start,counterStart:normalizeDigits(e.target.value).replace(/\D/g,'').slice(0,7)})}/></label><label>توضیحات اختیاری<textarea value={start.note} onChange={e=>setStart({...start,note:e.target.value})}/></label><button disabled={busy}>{busy?'در حال ثبت…':'ثبت شروع شیفت'}</button></form>}
    {mode==='end'&&<form className="panel operator-form" onSubmit={submitEnd}><h3>پایان شیفت و ثبت معیوب</h3><label>تعداد سبد معیوب<NumericInput required inputMode="numeric" type="text" value={end.defects} onChange={e=>setEnd({...end,defects:e.target.value})}/></label>{status?.cleaningZone?<label className="cleaning-check"><input type="checkbox" checked={end.cleaningDone} onChange={e=>setEnd({...end,cleaningDone:e.target.checked})}/><span>نظافت Zone {status.cleaningZone} انجام شد</span></label>:<div className="hint">چرخه نظافت از ۵ مهر ۱۴۰۵ شروع می‌شود.</div>}<label>توضیحات اختیاری<textarea value={end.note} onChange={e=>setEnd({...end,note:e.target.value})}/></label><button disabled={busy}>{busy?'در حال ثبت…':'ثبت پایان شیفت'}</button></form>}
    {mode==='sale'&&<SaleEntry products={products} customers={customers} setCustomers={setCustomers} onSaved={load} busy={busy} setBusy={setBusy} setError={setError} setOk={setOk}/>}</Page>
}
